[dimensions]
system_message = """
You are a helpful assistant that extracts categories from a consultant CVs.
"""
human_message = """
Below you have a list of CVs about consultants. Can you please extract the main categories from these CVs?

The categories can be for example:
- location
    description: The location of the consultant
- industry
    description: The industry of the consultant
- company size
    description: The size of the company the consultant works at
- job title
    description: The job title of the consultant
- years of experience
    description: The years of experience of the consultant
- education
    description: The education of the consultant
- skills
    description: The skills of the consultant
- interests
    description: The skills of the consultant
There are more categories that you have to extract. So you are not expected to just extract the ones listed above.

Also make sure you provide a description for each category.

{cvs}
"""

[questions]
system_message = """
You are a helpful assistant that generates questions based on the category extracted from a consultant CVs.
"""
human_message = """
Below you have a list of categories extracted from a consultant CVs. Can you please generate questions for each category?

Some examples categories are:
# Industry
- What is the industry you are interested in?
# Company size
- Which is the size of your company?
- How many employees does your company have?
# Job title
- What is the job title you are looking for?
- Which is the consultant role you are looking for?
# Years of experience
- What is the years of experience you are looking for?
# Location
- Which is the location you are looking for?

When you generate the questions, make sure you provide a suitable question for the category. 

Also make sure that the questions are focused on the needs of the customer of the consultant.
The questions should be about what the customer is looking for in a consultant.
So if there are questions about volunteering experience, make sure that the customer is asked about which volunteering experience the consultant should have.
The same applies for aspirations ("Which aspirations would you like the consultant to have?") and other categories.
The scenario is that of a chatbot that is asking a potential customer about their needs.

```json
{category}
```
"""

[dimensions_assigner]
system_message = """
You are a helpful assistant that assigns single categories to a consultant.
"""
human_message = """
Below you have a single category. Can you please check if this single category apply to the consultant?

The category element is:

{category_element}

The consultant description is:
```
{consultant}
```

You should output the category element if it applies to the consultant. Otherwise, do not output anything.

"""

[questions_order]
system_message = """
You are a helpful assistant that orders questions based on the category.
"""
human_message = """
Below you have a list of questions that should help a customer to find a consultant. 
Can you please order them based on the category so that the most relevant questions are asked first?

The sorting should give precedence to the questions related to a more general category first and then navigate into the more specific ones.

A more general category is for example:
- industry

A more specific category is for example:
- volunteering experience

The general idea is to sort the questions in a way that most customers wanting to find a consultant will ask first.

The sorting should give precedence to the questions related to a more general category first and then navigate into the more specific ones.

{questions}
"""
