[dimensions]
system_message = """
You are a helpful assistant that extracts categories from consultant CVs.
"""
human_message = """
Below you have a list of CVs about consultants. Please extract the main dimensions for categorization from these CVs.

The dimensions for categorization can be for example:
- location
    description: The location of the consultant
- industry
    description: The industry of the consultant
- company size
    description: The size of the company the consultant works at
- job title
    description: The job title of the consultant
- years of experience
    description: The years of experience of the consultant
- education
    description: The education of the consultant
- skills
    description: The skills of the consultant
- interests
    description: The skills of the consultant

There are more categories that you have to extract. So you are not expected to just extract the ones listed above.

Also make sure you provide a description for each category.

You will also be asked to extract the list of values for each category.

For example, if the category is "industry", the list of values could be:
- IT
- Finance
- Consulting

For example, if the category is "company size", the list of values could be:
- 1-10 employees
- 11-50 employees
- 51-200 employees
- 201-500 employees
- 501-1000 employees
- More than 1000 employees

{cvs}
"""

[cv_summary]
system_message = """
You are a helpful assistant that summarizes a single consultant CV.
"""
human_message = """
Below you have a consultant CV. Please summarize the CV in around 100 words.

{cv}
"""


[dimension_option_deduplication]
system_message = """
You are a helpful assistant that deduplicates the list of values for a category.
"""
human_message = """
Below you have a list of values for a category. Please deduplicate the list of values.
The list of values can be found between === start category_name === and === end category_name ===. 
The name of the category is: {category_name}
The description of the category is: {category_description}

The list of values is:
=== start category_name ===
{category_list_of_values}
=== end category_name ===

Here is an example on how to deduplicate the list of values:
The name of the category is: location
=== start category_name ===
- Greater London, England
- London Area, United Kingdom
- London, England
- London, England, United Kingdom
=== end category_name ===

All of these are the same location. So you should deduplicate them and output the following:
=== start category_name ===
- Greater London, England
=== end category_name ===

Here is another example:
The name of the category is: job title
=== start category_name ===
- Software Engineer
- Software Developer
=== end category_name ===

This is a very similar job title. You can output the following:
=== start category_name ===
- Software Engineer
=== end category_name ===

Please make sure that you never retrieve more that 20 values per category.

"""


[questions]
system_message = """
You are a helpful assistant that generates questions based on the category extracted from consultant CVs.
"""
human_message = """
Below you have a list of categories extracted from a consultant CVs. Can you please generate questions for each category?

Some examples categories are:
# Industry
- What is the industry you are interested in?
# Company size
- Which is the size of your company?
- How many employees does your company have?
# Job title
- What is the job title you are looking for?
- Which is the consultant role you are looking for?
# Years of experience
- What is the years of experience you are looking for?
# Location
- Which is the location you are looking for?

When you generate the questions, make sure you provide a suitable question for the category. 

Also make sure that the questions are focused on the needs of the customer of the consultant.
The questions should be about what the customer is looking for in a consultant.
So if there are questions about volunteering experience, make sure that the customer is asked about which volunteering experience the consultant should have.
The same applies for aspirations ("Which aspirations would you like the consultant to have?") and other categories.
The scenario is that of a chatbot that is asking a potential customer about their needs.

Category name: {category_name}
Category description: {category_description}
Category list of values:
{category_list_of_values}
"""

[dimensions_assigner]
system_message = """
You are a helpful assistant that assigns single categories to a consultant.
"""
human_message = """
Below you have a single category. Can you please check if this single category apply to the consultant?

The category element is:

{category_element}

The consultant description is:
```
{consultant}
```

You should output the category element if it applies to the consultant. Otherwise, do not output anything.

"""

[questions_order]
system_message = """
You are a helpful assistant that orders questions based on the category.
"""
human_message = """
Below you have a list of questions that should help a customer to find a consultant. 
Can you please order them based on the category so that the most relevant questions are asked first?

The sorting should give precedence to the questions related to a more general category first and then navigate into the more specific ones.

A more general category is for example:
- industry

A more specific category is for example:
- volunteering experience

The general idea is to sort the questions in a way that most customers wanting to find a consultant will ask first.

The sorting should give precedence to the questions related to a more general category first and then navigate into the more specific ones.

{questions}
"""
