-- These are the tables that are used to store the session datas

CREATE TABLE PUBLIC.TB_SESSION (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    USER_EMAIL CHARACTER VARYING(256) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NULL
);

CREATE TABLE PUBLIC.TB_SESSION_QUESTION (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    SESSION_ID INTEGER NOT NULL,
    CATEGORY_QUESTION_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SESSION_ID
        FOREIGN KEY (SESSION_ID) REFERENCES PUBLIC.TB_SESSION (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT CATEGORY_QUESTION_ID
        FOREIGN KEY (CATEGORY_QUESTION_ID) REFERENCES PUBLIC.TB_CATEGORY_QUESTION (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE PUBLIC.TB_SESSION_QUESTION_RESPONSES (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    SESSION_QUESTION_ID INTEGER NOT NULL,
    CATEGORY_ITEM_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SESSION_QUESTION_ID
        FOREIGN KEY (SESSION_QUESTION_ID) REFERENCES PUBLIC.TB_SESSION_QUESTION (ID)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT CATEGORY_ITEM_ID
        FOREIGN KEY (CATEGORY_ITEM_ID) REFERENCES PUBLIC.TB_CATEGORY_ITEM (ID)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);