-- Consultant

CREATE TABLE PUBLIC.TB_SKILL (
	ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	SKILL_NAME CHARACTER VARYING(256) UNIQUE NOT NULL
);

CREATE TABLE PUBLIC.TB_CONSULTANT (
	ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	GIVEN_NAME CHARACTER VARYING(256) NOT NULL,
	SURNAME CHARACTER VARYING(256) NOT NULL,
	EMAIL CHARACTER VARYING(256) UNIQUE NOT NULL,
	CV TEXT NOT NULL,
	INDUSTRY_NAME CHARACTER VARYING(256) NULL,
	GEO_LOCATION CHARACTER VARYING(256) NULL,
	LINKEDIN_PROFILE_URL CHARACTER VARYING(1024) NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NULL,
	CONSTRAINT email_format CHECK (
        EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    )
);

CREATE TABLE PUBLIC.TB_CONSULTANT_SKILL (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CONSULTANT_ID INTEGER NOT NULL,
    SKILL_ID INTEGER NOT NULL,
    CONSTRAINT CONSULTANT_SKILL_CONSULTANT_ID
        FOREIGN KEY (CONSULTANT_ID) REFERENCES PUBLIC.TB_CONSULTANT (ID)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT CONSULTANT_SKILL_SKILL_ID
        FOREIGN KEY (SKILL_ID) REFERENCES PUBLIC.TB_SKILL (ID)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT UNIQUE_CONSULTANT_SKILL
        UNIQUE (CONSULTANT_ID, SKILL_ID)
);

CREATE TABLE PUBLIC.TB_INDUSTRY (
	ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	INDUSTRY_NAME CHARACTER VARYING(256) NOT NULL
);

CREATE TABLE PUBLIC.TB_COMPANY (
	ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	COMPANY_NAME CHARACTER VARYING(256) UNIQUE NOT NULL
);

CREATE TABLE PUBLIC.TB_COMPANY_INDUSTRY (
	ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	INDUSTRY_ID INTEGER NOT NULL,
	COMPANY_ID INTEGER NOT NULL,
	CONSTRAINT COMPANY_INDUSTRY_COMPANY_ID
		FOREIGN KEY (COMPANY_ID) REFERENCES PUBLIC.TB_COMPANY (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT COMPANY_INDUSTRY_INDUSTRY_ID
		FOREIGN KEY (INDUSTRY_ID) REFERENCES PUBLIC.TB_INDUSTRY (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE UNIQUE INDEX unique_email_ci ON PUBLIC.TB_CONSULTANT (LOWER(EMAIL));

CREATE TABLE PUBLIC.TB_CONSULTANT_EXPERIENCE (
	ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CONSULTANT_ID INTEGER NOT NULL,
	TITLE CHARACTER VARYING(256) NULL,
	LOCATION CHARACTER VARYING(256) NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NULL,
	COMPANY_ID INTEGER NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NULL,
	CONSTRAINT CONSULTANT_ID
		FOREIGN KEY (CONSULTANT_ID) REFERENCES PUBLIC.TB_CONSULTANT (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT COMPANY_ID
		FOREIGN KEY (COMPANY_ID) REFERENCES PUBLIC.TB_COMPANY (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

-- CREATE TABLE PUBLIC.TB_SESSION_CONSULTANT_RATING (
-- 	ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
-- 	CONSULTANT_ID INTEGER NOT NULL,
-- 	SESSION_ID CHARACTER VARYING(36) NOT NULL,
-- 	REASONING TEXT NOT NULL,
-- 	RATING CHARACTER VARYING(20) NOT NULL,
-- 	RATING_NUMBER SMALLINT NOT NULL CHECK (RATING_NUMBER BETWEEN 1 AND 5),
-- 	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
-- 	UPDATED_AT TIMESTAMP NULL,
-- 	CONSTRAINT CONSULTANT_ID
-- 		FOREIGN KEY (CONSULTANT_ID) REFERENCES PUBLIC.TB_CONSULTANT (ID)
-- 		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
-- );

-- Category related tables

CREATE TABLE PUBLIC.TB_CATEGORY (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME CHARACTER VARYING(256) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NULL
);

-- unique constraint on name
CREATE UNIQUE INDEX unique_category_name ON PUBLIC.TB_CATEGORY (NAME);

CREATE TABLE PUBLIC.TB_CATEGORY_QUESTION (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CATEGORY_ID INTEGER NOT NULL,
    QUESTION TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NULL,
    CONSTRAINT CATEGORY_ID
        FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.TB_CATEGORY (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE PUBLIC.TB_CATEGORY_ITEM (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CATEGORY_ID INTEGER NOT NULL,
    ITEM CHARACTER VARYING(256) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NULL,
    CONSTRAINT CATEGORY_ID
		FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.TB_CATEGORY (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

-- unique constrait on category_id and item
CREATE UNIQUE INDEX unique_category_item ON PUBLIC.TB_CATEGORY_ITEM (CATEGORY_ID, ITEM);

CREATE TABLE PUBLIC.TB_CONSULTANT_CATEGORY_ITEM_ASSIGNMENT (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CONSULTANT_ID INTEGER NOT NULL,
    CATEGORY_ITEM_ID INTEGER NOT NULL,
    CONSTRAINT CONSULTANT_ID
		FOREIGN KEY (CONSULTANT_ID) REFERENCES PUBLIC.TB_CONSULTANT (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT CATEGORY_ITEM_ID
		FOREIGN KEY (CATEGORY_ITEM_ID) REFERENCES PUBLIC.TB_CATEGORY_ITEM (ID)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

-- unique constrait on CONSULTANT_ID and CATEGORY_ITEM_ID
CREATE UNIQUE INDEX unique_consultant_category_item ON PUBLIC.TB_CONSULTANT_CATEGORY_ITEM_ASSIGNMENT (CONSULTANT_ID, CATEGORY_ITEM_ID);


